### ISSUE TITLE
Messages are "retried" only once despite my configuration (retries: 3)

### ISSUE THREAD

**Issue by ypereirareis** [odolbeau/rabbit-mq-admin-toolkit#31]
Hi !

It seems there is (or I have) a problem with retry (more than once).

## Config

I use these libs and versions:

```
"swarrot/swarrot-bundle": "1.4.1",
"php-amqplib/php-amqplib": "^2.6",
"odolbeau/rabbit-mq-admin-toolkit": "^3.2"
```

I have this configuration for `odolbeau/rabbit-mq-admin-toolkit`:

```
'/':
    parameters:
        with_dl: false
        with_unroutable: false

    exchanges:
        benchmark_test_1:
            type: direct
            durable: true

    queues:
        benchmark_test_1:
            durable: true
            retries: [5, 25, 100]
            bindings:
                - exchange: benchmark_test_1
                  routing_key: benchmark_test_1
```

It gives me this output

```
With DL: false
With Unroutable: false
Create exchange benchmark_test_1
Create exchange dl
Create queue benchmark_test_1
Create queue benchmark_test_1_dl
Create binding between exchange dl and queue benchmark_test_1_dl (with routing_key: benchmark_test_1)
Create exchange retry
Create queue benchmark_test_1_retry_1
Create binding between exchange retry and queue benchmark_test_1_retry_1 (with routing_key: benchmark_test_1_retry_1)
Create binding between exchange retry and queue benchmark_test_1 (with routing_key: benchmark_test_1)
Create exchange retry
Create queue benchmark_test_1_retry_2
Create binding between exchange retry and queue benchmark_test_1_retry_2 (with routing_key: benchmark_test_1_retry_2)
Create binding between exchange retry and queue benchmark_test_1 (with routing_key: benchmark_test_1)
Create exchange retry
Create queue benchmark_test_1_retry_3
Create binding between exchange retry and queue benchmark_test_1_retry_3 (with routing_key: benchmark_test_1_retry_3)
Create binding between exchange retry and queue benchmark_test_1 (with routing_key: benchmark_test_1)
Create binding between exchange benchmark_test_1 and queue benchmark_test_1 (with routing_key: benchmark_test_1)
```

I my swarrot bundle configuration I have:

```
swarrot:
    provider: amqp_lib
    default_connection: rabbitmq
    default_command: swarrot.command.base
    connections:
        rabbitmq:
            host: rabbitmq
            port: 5672 # 15672
            login: rbu
            password: rbp
            vhost: '/'
    consumers:
        test_consume_quickly: # name of the consumer
            processor: processor.test_consume_quickly # name of the service
            extras:
                poll_interval: 500000
                requeue_on_error: false
            middleware_stack:
                - configurator: swarrot.processor.signal_handler
                - configurator: swarrot.processor.max_messages
                  extras:
                    max_messages: 10
                - configurator: swarrot.processor.max_execution_time
                  extras:
                    max_execution_time: 30
                - configurator: swarrot.processor.memory_limit
                  extras:
                      memory_limit: 50
                - configurator: swarrot.processor.exception_catcher
                - configurator: swarrot.processor.ack
                - configurator: swarrot.processor.retry
                  extras:
                    retry_exchange: 'retry'
                    retry_attempts: 3
                    retry_routing_key_pattern: 'benchmark_test_1_retry_%%attempt%%'


    messages_types:
        my_publisher:
            connection: rabbitmq # use the default connection by default
            exchange: benchmark_test_1
            routing_key: benchmark_test_1
```

## Problem

My consumer raise an expcetion.
The message goes to queue **benchmark_test_1_retry_1**
The message is sent back into **benchmark_test_1**
My consumer raise an expcetion.
And..... the message goes to queue **benchmark_test_1_dl**

But should go into queue **benchmark_test_1_retry_2** then **benchmark_test_1_retry_3**

I don't understand why...
Any idea what going on ?

Thanks !
