### ISSUE TITLE
Naming pattern

### ISSUE THREAD

**Issue by piotrbrzezina** [odolbeau/rabbit-mq-admin-toolkit#42]
Hi 

On the beginning, I want to thanks for this great library. 

I would like to know your opinion about what you think about adding to the configuration the possibility of creating name patterns for the queue dl and retry
curently thay are hardcoded to:

`$retryQueueName = $name.'_retry_'.$retries[$i];`
`$this->createQueue($name.'_dl', array(`
`$this->createQueue($name.'_delay_'.$delay, array(`

maybe we can create config value that can be overridden in a config file for this hardcoded string? 
for example
```    
parameters:
      dl_queue_patern: '%%queue_name%%_dl'
      retry_queue_patern: '%%queue_name%%_retry_%%retries%%'
      retry_queue_patern: '%%queue_name%%_delay_%%delay%%'
```

what do you think about that?
